<?php

namespace Database\Seeders;

use App\Models\Color;
use Illuminate\Database\Seeder;

class ColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $colors =  [
           ['title'=> "AliceBlue"],
           ['title'=> "AntiqueWhite"],
           ['title'=> "Aqua"],
           ['title'=> "Aquamarine"],
           ['title'=> "Azure"],
           ['title'=> "Beige"],
           ['title'=> "Bisque"],
           ['title'=> "Black"],
           ['title'=> "BlanchedAlmond"],
           ['title'=> "Blue"],
           ['title'=> "BlueViolet"],
           ['title'=> "Brown"],
           ['title'=> "BurlyWood"],
           ['title'=> "CadetBlue"],
           ['title'=> "Chartreuse"],
           ['title'=> "Chocolate"],
           ['title'=> "Coral"],
           ['title'=> "CornflowerBlue"],
           ['title'=> "Cornsilk"],
           ['title'=> "Crimson"],
           ['title'=> "Cyan"],
           ['title'=> "DarkBlue"],
           ['title'=> "DarkCyan"],
           ['title'=> "DarkGoldenRod"],
           ['title'=> "DarkGray"],
           ['title'=> "DarkGrey"],
           ['title'=> "DarkGreen"],
           ['title'=> "DarkKhaki"],
           ['title'=> "DarkMagenta"],
           ['title'=> "DarkOliveGreen"],
           ['title'=> "DarkOrange"],
           ['title'=> "DarkOrchid"],
           ['title'=> "DarkRed"],
           ['title'=> "DarkSalmon"],
           ['title'=> "DarkSeaGreen"],
           ['title'=> "DarkSlateBlue"],
           ['title'=> "DarkSlateGray"],
           ['title'=> "DarkSlateGrey"],
           ['title'=> "DarkTurquoise"],
           ['title'=> "DarkViolet"],
           ['title'=> "DeepPink"],
           ['title'=> "DeepSkyBlue"],
           ['title'=> "DimGray"],
           ['title'=> "DimGrey"],
           ['title'=> "DodgerBlue"],
           ['title'=> "FireBrick"],
           ['title'=> "FloralWhite"],
           ['title'=> "ForestGreen"],
           ['title'=> "Fuchsia"],
           ['title'=> "Gainsboro"],
           ['title'=> "GhostWhite"],
           ['title'=> "Gold"],
           ['title'=> "GoldenRod"],
           ['title'=> "Gray"],
           ['title'=> "Grey"],
           ['title'=> "Green"],
           ['title'=> "GreenYellow"],
           ['title'=> "HoneyDew"],
           ['title'=> "HotPink"],
           ['title'=> "IndianRed"],
           ['title'=> "Indigo"],
           ['title'=> "Ivory"],
           ['title'=> "Khaki"],
           ['title'=> "Lavender"],
           ['title'=> "LavenderBlush"],
           ['title'=> "LawnGreen"],
           ['title'=> "LemonChiffon"],
           ['title'=> "LightBlue"],
           ['title'=> "LightCoral"],
           ['title'=> "LightCyan"],
           ['title'=> "LightGoldenRodYellow"],
           ['title'=> "LightGray"],
           ['title'=> "LightGrey"],
           ['title'=> "LightGreen"],
           ['title'=> "LightPink"],
           ['title'=> "LightSalmon"],
           ['title'=> "LightSeaGreen"],
           ['title'=> "LightSkyBlue"],
           ['title'=> "LightSlateGray"],
           ['title'=> "LightSlateGrey"],
           ['title'=> "LightSteelBlue"],
           ['title'=> "LightYellow"],
           ['title'=> "Lime"],
           ['title'=> "LimeGreen"],
           ['title'=> "Linen"],
           ['title'=> "Magenta"],
           ['title'=> "Maroon"],
           ['title'=> "MediumAquaMarine"],
           ['title'=> "MediumBlue"],
           ['title'=> "MediumOrchid"],
           ['title'=> "MediumPurple"],
           ['title'=> "MediumSeaGreen"],
           ['title'=> "MediumSlateBlue"],
           ['title'=> "MediumSpringGreen"],
           ['title'=> "MediumTurquoise"],
           ['title'=> "MediumVioletRed"],
           ['title'=> "MidnightBlue"],
           ['title'=> "MintCream"],
           ['title'=> "MistyRose"],
           ['title'=> "Moccasin"],
           ['title'=> "NavajoWhite"],
           ['title'=> "Navy"],
           ['title'=> "OldLace"],
           ['title'=> "Olive"],
           ['title'=> "OliveDrab"],
           ['title'=> "Orange"],
           ['title'=> "OrangeRed"],
           ['title'=> "Orchid"],
           ['title'=> "PaleGoldenRod"],
           ['title'=> "PaleGreen"],
           ['title'=> "PaleTurquoise"],
           ['title'=> "PaleVioletRed"],
           ['title'=> "PapayaWhip"],
           ['title'=> "PeachPuff"],
           ['title'=> "Peru"],
           ['title'=> "Pink"],
           ['title'=> "Plum"],
           ['title'=> "PowderBlue"],
           ['title'=> "Purple"],
           ['title'=> "RebeccaPurple"],
           ['title'=> "Red"],
           ['title'=> "RosyBrown"],
           ['title'=> "RoyalBlue"],
           ['title'=> "SaddleBrown"],
           ['title'=> "Salmon"],
           ['title'=> "SandyBrown"],
           ['title'=> "SeaGreen"],
           ['title'=> "SeaShell"],
           ['title'=> "Sienna"],
           ['title'=> "Silver"],
           ['title'=> "SkyBlue"],
           ['title'=> "SlateBlue"],
           ['title'=> "SlateGray"],
           ['title'=> "SlateGrey"],
           ['title'=> "Snow"],
           ['title'=> "SpringGreen"],
           ['title'=> "SteelBlue"],
           ['title'=> "Tan"],
           ['title'=> "Teal"],
           ['title'=> "Thistle"],
           ['title'=> "Tomato"],
           ['title'=> "Turquoise"],
           ['title'=> "Violet"],
           ['title'=> "Wheat"],
           ['title'=> "White"],
           ['title'=> "WhiteSmoke"],
           ['title'=> "Yellow"],
           ['title'=> "YellowGreen"],
          ];
        // Color::factory()->count(10)->create();
        Color::insert($colors);
    }
}
